"""empty message

Revision ID: 6ff42dd2ba5d
Revises: ef7007a9a2e3
Create Date: 2025-07-16 11:12:35.561772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff42dd2ba5d'
down_revision = 'ef7007a9a2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('mensagem')
        batch_op.drop_column('respostas')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('respostas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mensagem', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('texto')

    # ### end Alembic commands ###
