"""iniciando o db, criando tabela Wiki

Revision ID: ef7007a9a2e3
Revises: 
Create Date: 2025-07-10 00:31:50.507870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7007a9a2e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('respostas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki')
    # ### end Alembic commands ###
